Feat/5 workspace api
KNU-Finnect/finnect_backend pull request #53
Opened 2024-05-12 10:50 UTC by wgwjh05169

**1.1.2 PR Template**

### ✨ 작업 내용
---
- 워크스페이스와 멤버에 대한 REST API를 제공합니다.

### ✨ 참고 사항
---
- soft delete을 적용하지 않았습니다.

### ⏰ 현재 버그
---

2024-05-12 12:11 UTC, sin6708k requested changes

2024-05-12 12:11 UTC, sin6708k commented on src/main/java/com/finnect/common/Response.java
상희가 정한 ApiUtils로 바꿔야 할 듯

2024-05-12 12:11 UTC, sin6708k commented on src/main/java/com/finnect/workspace/adaptor/out/persistence/MemberJpaEntity.java
> +public class MemberJpaEntity implements MemberState {
JpaEntity 대신 Entity로 네이밍하기로 했었음

2024-05-15 07:39 UTC, wgwjh05169 commented on src/main/java/com/finnect/common/Response.java
통일완료

2024-05-15 07:40 UTC, wgwjh05169 commented on src/main/java/com/finnect/workspace/adaptor/out/persistence/MemberJpaEntity.java
> +public class MemberJpaEntity implements MemberState {
반영했어용

2024-05-15 08:18 UTC, sanghee0820 approved these changes
LGTM

2024-05-15 09:34 UTC, sin6708k approved these changes

2024-05-16 12:03 UTC, merged